=== carlosrzdr/Practica1DIS/almacen.dtd
<!DOCTYPE Almacen
[
<!ELEMENT Almacen (Productos,Clientes,Pedidos)>

<!ELEMENT Productos (Producto+)>
<!ELEMENT Producto (Nombre,Descripcion, Stock, Pendientes, Localizacion)>
<!ELEMENT Nombre (#PCDATA)>
<!ELEMENT Descripcion (#PCDATA)>
<!ELEMENT Stock (#PCDATA)>
<!ELEMENT Pendientes (#PCDATA)>
<!ELEMENT Localizacion (Pasillo, Estanteria, Estante)>
<!ELEMENT Pasillo (#PCDATA)>
<!ELEMENT Estanteria (#PCDATA)>
<!ELEMENT Estante (#PCDATA)>

<!ELEMENT Clientes (Cliente*)>
<!ELEMENT Cliente (Nombre, Apellidos, Email, Telefono, Direccion)>
<!ELEMENT Nombre (#PCDATA)>
<!ELEMENT Apellidos (#PCDATA)>
<!ELEMENT Email (#PCDATA)>
<!ELEMENT Telefono (#PCDATA)>
<!ELEMENT Direccion (Calle, Numero, CodigoPostal, Poblacion, Pais)>
<!ELEMENT Calle (#PCDATA)>
<!ELEMENT Numero (#PCDATA)>
<!ELEMENT CodigoPostal (#PCDATA)>
<!ELEMENT Poblacion (#PCDATA)>
<!ELEMENT Pais (#PCDATA)>

<!ELEMENT Pedidos (Pedido*)>
<!ELEMENT Pedido (Productos, Destinatario, Fecha, Direccion)>
<!ELEMENT Productos (Producto+)>
<!ELEMENT Producto (Info, Cantidad)>
<!ELEMENT Cantidad (#PCDATA)>
<!ELEMENT Info (#PCDATA)>
<!ELEMENT Destinatario (#PCDATA)>
<!ELEMENT Fecha (#PCDATA)>
<!ELEMENT Direccion (Calle, Numero, CodigoPostal, Poblacion, Pais)>
<!ELEMENT Calle (#PCDATA)>
<!ELEMENT Numero (#PCDATA)>
<!ELEMENT CodigoPostal (#PCDATA)>
<!ELEMENT Poblacion (#PCDATA)>
<!ELEMENT Pais (#PCDATA)>

<!ATTLIST Producto Codigo ID #REQUIRED>
<!ATTLIST Cliente Id ID #REQUIRED>
<!ATTLIST Pedido Id ID #REQUIRED>

]>

=== carlosrzdr/Practica1DIS/com.dis.practica1/almacen.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Almacen SYSTEM "Almacen.dtd">
<Almacen>
          <Productos>
                    <Producto Codigo="123">
                              <NombreProducto>fg</NombreProducto>
                              <Descripcion>f</Descripcion>
                              <Stock>f</Stock>
                              <Pendientes>f</Pendientes>
                              <Localizacion>
                                        <Pasillo>f</Pasillo>
                                        <Estanteria>f</Estanteria>
                                        <Estante>f</Estante>
                              </Localizacion>
                    </Producto>
          </Productos>
          <Clientes>
                    <Cliente Id="12">
                              <Nombre>12</Nombre>
                              <Apellidos>f</Apellidos>
                              <Email>f</Email>
                              <Telefono>f</Telefono>
                              <Direccion>
                                        <Calle>f</Calle>
                                        <Numero>f</Numero>
                                        <CodigoPostal>f</CodigoPostal>
                                        <Poblacion>f</Poblacion>
                                        <Pais>f</Pais>
                              </Direccion>
                    </Cliente>
          </Clientes>
          <Pedidos>
                    <Producto Codigo="23">
                              <NombreProducto>z</NombreProducto>
                              <Descripcion>z</Descripcion>
                              <Stock>z</Stock>
                              <Pendientes>z</Pendientes>
                              <Localizacion>
                                        <Pasillo>z</Pasillo>
                                        <Estanteria>z</Estanteria>
                                        <Estante>z</Estante>
                              </Localizacion>
                    </Producto>
          </Pedidos>
</Almacen>
